version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      APP_NAME: "MiniProj2"
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sostthetraitor
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mado
    ports:
      - "8080:8080"
    depends_on:
      - db
      - mongo
    restart: always

  db:
    image: postgres
    container_name: db_container
    environment:
      POSTGRES_DB: sostthetraitor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mado
    ports:
      - "5432:5432"
    restart: always

  # MongoDB
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "9000:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

